### PR TITLE
Added a new command line flag for reducing verbosity

### PR DESCRIPTION
**Pull request by dishad**
Added a check for command options so that HTMLHint will run on the correct directory when using a one of the flags. The new command line flag gives users the option to either have HTMLHint tell them their html passed without logging `No Problem.`

### CODE REVIEW

**Comment by yaniswang** [comment]
You want show no message when hint success?
Why?

**Comment by dishad** [comment]
I think that the only reason HTMLHint should print out a message is when it fails so that it can show the user where their errors are. In many cases with linters there is no success message being printed because many people will automatically assume that no errors were detected.

**Comment by yaniswang** [comment]
Why no logs?
If used in build system, the return code works well.

**Comment by dishad** [comment]
I think there are cases where both printing and not printing work well, but in the end its all preference. That's why it was added as a command line flag, to give people the option of whether or not they would like the success message to print.

**Comment by kethinov** [comment]
For what it's worth, other linting tools typically show no output at all by default when there is no problem with the code.

Personally I would change the default to just show no output at all when the code passes all rules. But failing that, an option would be nice.

**Comment by waldyrious** [comment]
I personally prefer tools that err on the side of clarity than conciseness. That said, I agree that an option for silent (successful) output would be nice.

**Comment by yaniswang** [comment]
jshint show no output when is no problem.

	E:\github\HTMLHint>jshint index.js
	

csslint will show a message:

	E:\github\HTMLHint>csslint test.css

	csslint: No errors in E:\github\HTMLHint\test.css.

**Comment by alallier** [comment]
I believe the  new command line flag that gives the user the option to use HTMLHINT without logging is desirable. Also this is the behavior of most linters. Adding a flag allows for all cases and will satisfy everyone's wants and needs.

**Comment by yaniswang** [comment]
I donot know the silent mode is used for what case?

**Comment by alallier** [comment]
The case is when you don't want any output unless something is wrong, instead of always giving the success message.

**Comment by yaniswang** [comment]
It is used for human view? or in build system?

**Comment by kethinov** [comment]
eslint also shows no output with no problem, just like jshint.

If you don't want to change the default, that's understandable, but an option to suppress the output would still be useful.

**Comment by yaniswang** [comment]
Support silent mode is no problem, but i interested in what the silent mode is used for what case?

**Comment by kethinov** [comment]
Ah I see. Both in build systems and manual use in my case. Personally the biggest reason I'd like to see it as an option is because the other two linters I currently use (lesshint and eslint) do not have any no problem output and I'd just prefer to keep all 3 consistent in my build process.

**Pull request closed without merging**
