### PR TITLE
feat(htmlhintrc): allow comments in json similar to jshintrc

### PR DESCRIPTION
**Pull request by doshprompt**
[Review on Reviewable](https://reviewable.io/reviews/yaniswang/htmlhint/60)

### CODE REVIEW

**Comment by doshprompt** [comment]
```js
{
  /*
   * PERFORMANCE
   * =================
   */

  // Disallow script tags in <head />
  "head-script-disabled": true
}
```

**Comment by doshprompt** [comment]
travis fails due to strip-json-comment deps format not supported by package.json of older npm version.

Depends on #62

**Comment by yaniswang** [comment]
Why remove csslint dependency?

**Comment by yaniswang** [comment]
Now fixed: https://github.com/yaniswang/HTMLHint/commit/921a842f22df8d7eb266d23a6e200ec36b3a4214

**Pull request closed without merging**
